version: '3'
services:
  osrm:
    image: ghcr.io/project-osrm/osrm-backend
    command: osrm-routed --algorithm mld /data/kentucky-latest.osrm
    volumes:
      - ./docker/osrm/data:/data
    ports:
      - "5000:5000"
  vroom-backend:
    image: vroom-docker
    volumes:
      - ./docker/vroom/conf:/conf
    environment:
      - VROOM_ROUTER=osrm
    ports:
      - "3000:3000"
    depends_on:
      - osrm
  # vroom-frontend:
  #   image: iedmrc/vroom-frontend
  #   restart: always
  #   ports:
  #       - "9966:9966"
  #   depends_on:
  #       - osrm
  #       - vroom-backend
  # app:
  #   build: .
  #   command: gradio run app.py --share --port 7860
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "7860:7860"
  #   depends_on:
  #     - vroom-backend
  #     - osrm

