import os
from dotenv import load_dotenv
load_dotenv()

LOG_LEVEL = os.getenv('LOG_LEVEL','INFO')
OPENROUTESERVICE_API_KEY = os.getenv('OPENROUTESERVICE_API_KEY')
OPENROUTESERVICE_BASE_URL = os.getenv('OPENROUTESERVICE_API_URL')

ALLOW_POOLING = False
DEFAULT_VEHICLE_SIZE = 4
DAY_START_HOUR = 8
DAY_END_HOUR = 17

ADDRESS_STORE = "data/addresses.json"


